spring:
  application:
    name: user-service
  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port: 8082


#..............   CIRCUIT BREAKER CONFIG  .................#
resilience4j:
  circuitbreaker:
    instances:
      department-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallDurationThreshold: 2s
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always