apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server-app
  template:
    metadata:
      labels:
        app: cloud-config-server-app
    spec:
      containers:
      - name: cloud-config-server-app
        image: cskblackhawk/cloud-config-server:0.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9296


---

apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server-svc
spec:
  selector:
    app: cloud-config-server-app
  ports:
  - port: 80
    targetPort: 9296
